### ISSUE TITLE
会出现以下报错

### ISSUE THREAD

**Issue by dragonpapa47** [opensourceai/MRI-U-net#2]
E:\software\anaconda3\python.exe E:/workstorage/MRI-U-net-master/src/Main.py
E:\software\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
(2200, 512, 512, 1)
Traceback (most recent call last):
  File "E:/workstorage/MRI-U-net-master/src/Main.py", line 11, in <module>
    X, y = get_data()
  File "E:\workstorage\MRI-U-net-master\src\utils.py", line 70, in get_data
    label = encode_one_hot(label, 3)
  File "E:\workstorage\MRI-U-net-master\src\utils.py", line 86, in encode_one_hot
    x_tiled[:, :, :, i] = np.where(x_tiled[:, :, :, i] == i, 1, 0)
MemoryError

会出现这样的报错，不知道大家有没有遇到

**Comment by chenquan** [comment]
https://blog.csdn.net/BinChasing/article/details/53158889
检查一下是不是这个原因，这部分代码本身是不存在的
