### ISSUE TITLE
no such a director

### ISSUE THREAD

**Issue by victorchencai** [opensourceai/MRI-U-net#8]
请问我将百度网盘下载的U-NET2200_1.HF5更名为val_best_model.h5放入model目录下，运行还是报错。
已经在第一代以后。
请教一下~

runfile('C:/Users/Administrator/Desktop/MRI-U-net-master/src/Main.py', wdir='C:/Users/Administrator/Desktop/MRI-U-net-master/src')
=========          Get data            =========
(2200, 512, 512, 1)
(2200, 512, 512, 1)
(2200, 512, 512, 1)
=========Split train sets and test sets=========
=========          Build model         =========
=========       Start train model      =========
Train on 2156 samples, validate on 22 samples
Epoch 1/10
2155/2156 [============================>.] - ETA: 14s - loss: 0.0517 - accuracy: 0.9883    
Epoch 00001: val_loss improved from inf to 0.03988, saving model to model/val_best_model.h5
Traceback (most recent call last):

  File "<ipython-input-1-9ac01f1ecd2a>", line 1, in <module>
    runfile('C:/Users/Administrator/Desktop/MRI-U-net-master/src/Main.py', wdir='C:/Users/Administrator/Desktop/MRI-U-net-master/src')

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Administrator/Desktop/MRI-U-net-master/src/Main.py", line 29, in <module>
    model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=10, validation_split=0.01, callbacks=[ModelCheckpoint])

  File "C:\Users\Administrator\Desktop\MRI-U-net-master\src\UNetKeras.py", line 102, in fit
    class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 372, in fit
    prefix='val_')

  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 119, in __exit__
    next(self.gen)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_v2.py", line 685, in on_epoch
    self.callbacks.on_epoch_end(epoch, epoch_logs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 298, in on_epoch_end
    callback.on_epoch_end(epoch, logs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 965, in on_epoch_end
    self._save_model(epoch=epoch, logs=logs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\callbacks.py", line 1001, in _save_model
    self.model.save(filepath, overwrite=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\network.py", line 975, in save
    signatures, options)

  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 112, in save_model
    model, filepath, overwrite, include_optimizer)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 92, in save_model_to_hdf5
    f = h5py.File(filepath, mode='w')

  File "C:\ProgramData\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)

  File "C:\ProgramData\Anaconda3\lib\site-packages\h5py\_hl\files.py", line 176, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "h5py\h5f.pyx", line 105, in h5py.h5f.create

OSError: Unable to create file (unable to open file: name = 'model/val_best_model.h5', errno = 2, error message = 'No such file or directory', flags = 13, o_flags = 302)

**Comment by chenquan** [comment]
@victorchencai 

下载的模型,不是这样使用的.
直接使用模型进行预测,(在[README.md](https://github.com/opensourceai/MRI-U-net/blob/master/README.md)也有描述):
```python
from scipy import ndimage
import tensorflow as tf
import numpy as np

image = np.array(ndimage.imread("img.png", flatten=False))
image /=255.
image = np.expand_dims(image, -1)

model = tf.keras.model.load("model/model_final_time.h5") # 或者val_best_time.h5
pred = model.predict(image)
```
如果是迁移训练:
使用
```python
model = tf.keras.model.load("model/model_final_time.h5") # 或者val_best_time.h5
model.compile(optimizer=tf.keras.optimizers.Adam(lr=1e-5, beta_1=0.90, beta_2=0.90),
                loss="categorical_crossentropy",
                metrics=['accuracy'])
```
替换掉以下的代码

https://github.com/opensourceai/MRI-U-net/blob/026a57311dc20e96ec24638b9c3faaf9a2022fe8/src/Main.py#L22-L24

**Comment by chenquan** [comment]
@victorchencai 

如果问题解决咯,麻烦关闭一下Issues

**Comment by victorchencai** [comment]
好的，谢谢您，不好意思没有及时回复，祝一天愉快

**Comment by chenquan** [comment]
> 好的，谢谢您，不好意思没有及时回复，祝一天愉快

不客气，解决就好。

**Comment by WrenGhost** [comment]
求一下模型！万分感谢！！！
